<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="figures/PDSH-cover-small.png">

*このノートブックには、Jake VanderPlas による [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) からの抜粋が含まれています。コンテンツは利用可能です [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do).*

※テキストは[CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode)で、コードは[CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode)で公開しています。このコンテンツが役立つと思われる場合は、[CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode) による作業のサポートを検討してください!*

<!--ナビゲーション-->
< [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) | [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) | [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) >

<a href="https://colab.research.google.com/github/vitroid/PythonDataScienceHandbook/blob/ja/notebooks/02.02-The-Basics-Of-NumPy-Arrays.ipynb"><img align="left " src="https://colab.research.google.com/assets/colab-badge.svg" alt="Colab で開く" title="Google Colaboratory で開いて実行する"></a>


# NumPy 配列の基本

Python でのデータ操作は、NumPy 配列操作とほぼ同義です。Pandas ([Chapter 3](03.00-Introduction-to-Pandas.ipynb)) などの新しいツールでさえ、NumPy 配列を中心に構築されています。
このセクションでは、NumPy 配列操作を使用してデータとサブ配列にアクセスし、配列を分割、変形、結合する例をいくつか紹介します。
ここで示した操作の種類は、少し無味乾燥で陳腐に見えるかもしれませんが、本全体で使用される他の多くの例の構成要素を構成しています。
それらをよく知ってください！

ここでは、基本的な配列操作のいくつかのカテゴリについて説明します。

- *配列の属性*: 配列のサイズ、形状、メモリ消費量、およびデータ型の決定
- *配列のインデックス付け*: 個々の配列要素の値の取得と設定
- *配列のスライス*: 大きな配列内の小さなサブ配列の取得と設定
- *配列の再形成*: 特定の配列の形状を変更する
- *配列の結合と分割*: 複数の配列を 1 つに結合し、1 つの配列を複数に分割する

## NumPy 配列属性

最初に、いくつかの有用な配列属性について説明しましょう。
まず、1 次元、2 次元、および 3 次元配列の 3 つのランダム配列を定義します。
NumPy の乱数​​ジェネレーターを使用します。これは、このコードが実行されるたびに同じ乱数配列が生成されるように、設定値で *シード* します。

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

各配列には、属性 ``ndim`` (次元数)、``shape`` (各次元のサイズ)、および ``size`` (配列の合計サイズ) があります。

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


もう 1 つの便利な属性は、配列のデータ型である ``dtype`` です (以前に [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) で説明しました)。

In [3]:
print("dtype:", x3.dtype)

dtype: int64


その他の属性には、各配列要素のサイズ (バイト単位) をリストする ``itemsize`` と、配列の合計サイズ (バイト単位) をリストする ``nbytes`` が含まれます。

In [4]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


一般に、「nbytes」は「itemsize」×「size」に等しいと予想されます。

## 配列の索引付け: 単一要素へのアクセス

Python の標準的なリストのインデックス作成に精通している場合、NumPy でのインデックス作成は非常になじみ深いものです。
1 次元配列では、$i^{th}$ 値 (ゼロから数えて) は、Python リストと同様に、角括弧で目的のインデックスを指定することによってアクセスできます。

In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [7]:
x1[4]

7

配列の末尾からインデックスを付けるには、負のインデックスを使用できます。

In [8]:
x1[-1]

9

In [9]:
x1[-2]

7

多次元配列では、コンマで区切られたインデックスのタプルを使用して項目にアクセスできます。

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[0, 0]

3

In [12]:
x2[2, 0]

1

In [13]:
x2[2, -1]

7

上記のインデックス表記のいずれかを使用して、値を変更することもできます。

In [14]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Python のリストとは異なり、NumPy 配列の型は固定されていることに注意してください。
これは、たとえば、浮動小数点値を整数配列に挿入しようとすると、値が暗黙のうちに切り捨てられることを意味します。この動作に気付かないでください。

In [15]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## 配列のスライス: サブ配列へのアクセス

角括弧を使用して個々の配列要素にアクセスできるように、コロン (``:``) 文字でマークされた *slice* 表記で部分配列にアクセスするためにも使用できます。
NumPy スライス構文は、標準の Python リストの構文に従います。配列 ``x`` のスライスにアクセスするには、次のようにします:
``` python
x[start:stop:step]
```
これらのいずれかが指定されていない場合、値はデフォルトで ``start=0``, ``stop=``*``size of dimension``*, ``step=1`` になります。
1 次元および多次元でサブ配列にアクセスする方法を見ていきます。

### 1 次元部分配列

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [18]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [19]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [20]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [21]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

紛らわしい可能性があるケースは、``step`` 値が負の場合です。
この場合、 ``start`` と ``stop`` のデフォルトが入れ替わります。
これは、配列を逆にする便利な方法になります。

In [22]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### 多次元部分配列

多次元スライスも同様に機能し、複数のスライスはコンマで区切られます。
例えば：

In [24]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [25]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [26]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

最後に、部分配列の次元を一緒に逆にすることもできます。

In [27]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### 配列の行と列へのアクセス

一般的に必要なルーチンの 1 つは、配列の単一の行または列へのアクセスです。
これは、単一のコロン (``:``) でマークされた空のスライスを使用して、インデックス作成とスライスを組み合わせることで実行できます。

In [28]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [29]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


行アクセスの場合、よりコンパクトな構文のために空のスライスを省略できます。

In [30]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### コピーなしのビューとしてのサブアレイ

配列スライスについて知っておくべき重要で非常に役立つことの 1 つは、配列データの *コピー* ではなく *ビュー* を返すことです。
これは、NumPy 配列のスライスが Python のリストのスライスと異なる領域の 1 つです。リストでは、スライスはコピーになります。
前の 2 次元配列を考えてみましょう。

In [31]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


これから $2 \times 2$ サブ配列を抽出しましょう:

In [32]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


この部分配列を変更すると、元の配列が変更されていることがわかります。観察：

In [33]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


このデフォルトの動作は、実際には非常に便利です。つまり、大規模なデータセットを扱う場合、基になるデータ バッファーをコピーする必要なく、これらのデータセットの一部にアクセスして処理できるということです。

### 配列のコピーの作成

配列ビューの優れた機能にもかかわらず、代わりに配列または部分配列内のデータを明示的にコピーすると便利な場合があります。これは ``copy()`` メソッドで最も簡単に行うことができます:

In [35]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


この部分配列を変更しても、元の配列は変更されません。

In [36]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## 配列の再形成

もう 1 つの便利なタイプの操作は、配列の再形成です。
これを行う最も柔軟な方法は、reshape メソッドを使用することです。
たとえば、1 から 9 までの数字を $3 \times 3$ グリッドに配置する場合は、次のようにします。

In [38]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


これが機能するには、初期配列のサイズが再形成された配列のサイズと一致する必要があることに注意してください。
可能であれば、reshape メソッドは初期配列のコピーなしのビューを使用しますが、連続していないメモリ バッファでは常にそうとは限りません。

もう 1 つの一般的な再形成パターンは、1 次元配列を 2 次元の行または列行列に変換することです。
これは reshape メソッドで行うことができます。または、スライス操作内で newaxis キーワードを使用することでより簡単に行うことができます。

In [39]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [40]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [41]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [42]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

このタイプの変換は、本書の残りの部分で頻繁に見られます。

## 配列の連結と分割

これまでのルーチンはすべて、1 つの配列に対して機能していました。複数の配列を 1 つに結合することも、逆に 1 つの配列を複数の配列に分割することもできます。ここでは、これらの操作について説明します。

### 配列の連結

連結、または NumPy での 2 つの配列の結合は、主にルーチン ``np.concatenate``、``np.vstack``、および ``np.hstack`` を使用して実行されます。
np.concatenate は、最初の引数として配列のタプルまたはリストを取ります。

In [43]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

一度に 3 つ以上の配列を連結することもできます。

In [44]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


2 次元配列にも使用できます。

In [45]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [46]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

混合次元の配列を操作するには、 np.vstack (垂直スタック) および np.hstack (水平スタック) 関数を使用する方が明確です。

In [48]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [49]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

同様に、 ``np.dstack`` は 3 番目の軸に沿って配列をスタックします。

### 配列の分割

連結の反対は分割で、関数 np.split 、 np.hsplit 、および np.vsplit によって実装されます。これらのそれぞれについて、分割ポイントを与えるインデックスのリストを渡すことができます。

In [50]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


*N* 個の分割点は、*N + 1* 個のサブアレイにつながることに注意してください。
関連する関数 ``np.hsplit`` と ``np.vsplit`` は似ています:

In [51]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [53]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


同様に、 np.dsplit は 3 番目の軸に沿って配列を分割します。

<!--ナビゲーション-->
< [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) | [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) | [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) >

<a href="https://colab.research.google.com/github/vitroid/PythonDataScienceHandbook/blob/ja/notebooks/02.02-The-Basics-Of-NumPy-Arrays.ipynb"><img align="left " src="https://colab.research.google.com/assets/colab-badge.svg" alt="Colab で開く" title="Google Colaboratory で開いて実行する"></a>
